version: '3.8'
services:
  webapp:
    build: .
    environment:
      - WIMWB_ENV=prod
    command: "uvicorn wimwb.web:app"
    environment:
      - DATABASE_URI=${DATABASE_URI}
    ports:
      - "8000:3000"
    depends_on:
      - "mysql"
    networks:
      - wimwb
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "http://localhost:8000"]
  #   interval: 1m30s
  #   timeout: 10s
  #   retries: 3
  #   start_period: 40s
networks:
  wimwb:
    driver: bridge
